##### 疑问一 :

```java
/*
    疑问:
        下面的信息是通过printStackTrace方法打印出来的, 那么异常对象是从何而来呢?
        Exception in thread "main" java.lang.ArithmeticException: / by zero
        at Demo10.div(Demo10.java:7)
        at Demo10.main(Demo10.java:3)
 */
public class Demo10 {
    public static void main(String[] args) {
        div(4, 0);
    }

    public static void div(int i, int j){
        int k = i/j;
        System.out.println("k = " + k);
    }
}
```

* #### 我来解答 :

  ##### 当JVM运行到 i/j 这个语句的时候 , 发现 j 为0 , 除数为 0 在我们现实生活中是属于不正常的情况 , JVM 一旦发现了这种不正常情况的时候 , 那么它就会马上创建一个对应的异常对象 , 并且会调用这个异常对象的 printStackTrace 方法来处理 .

##### 疑问二 :

* ##### 感觉异常的处理没有多大作用 , 因为都是输出一句话而已?

```java
...
public static void div(int i, int j){
        int k = 0;
        try{
            k = i/j;
        }catch(ArithmeticException e){ // 重点关注下这里异常处理的代码
            System.out.println("toString: " + e.toString());
        }
        System.out.println("k = " + k);
    }
...
```

## 异常的处理

* ### 方式一 - 捕获处理

  * #### 格式 :

    ```java
    try{
        可能发生异常的代码;
    }catch(捕获的异常类型 变量名){
        处理异常的代码 ...
    }
    ```
  * #### 注意细节 :

    * ##### 01. 如果try块中代码发生了异常经过了处理之后 , 那么 try-catch 块外面的代码可以正常执行 .
    * ##### 02. 如果try块中出现了异常的代码 , 那么在try块中出现异常代码后面的代码就不会再执行了 .
    * ##### 03. 一个try块后面是可以跟有多个catch块的 , 也就是一个 try块可以捕获多种异常的类型 .
    * ##### 04. 一个try块可以捕获多种异常的类型 , 但是捕获的异常类型必须从小到大进行捕获 , 否则编译报错 .
  * #### 代码示例 :

    ```java
    public class Demo10 {
        public static void main(String[] args) {
            int[] niArr = null;
            div(4, 2, niArr);
        }

        public static void div(int i, int j, int[] niArr){
            int k = 0;
            try{
                k = i/j; // JVM在这句话的时候发现了不正常的情况, 那么就会创建一个对应的异常对象
                System.out.println("数组的长度: " + niArr.length);
            }catch(ArithmeticException e){
                // 处理异常的代码
                System.out.println("异常处理了 ...");
                System.out.println("toString: " + e.toString());
            }catch(NullPointerException e){
                System.out.println("出现了空指针异常 ...");
            }catch(Exception e){
                System.out.println("我是急诊室, 包治百病!");
            }
            System.out.println("k = " + k);
        }
    }
    ```
* ### 方式二 - 抛出处理



